### ISSUE TITLE
New directories are created alongside existing ones

### ISSUE THREAD

**Issue by TrifiAmanallah** [OutdatedGuy/package_rename#3]
When renaming an android package, a new file structure is created with a new MainActivity.kt
This implies two issues:

1. Existing user code in MainActivity.kt is ignored
2. The old files structure is kept alongside the new one

_For issue 1:_
The ideal approach would be to move the existing MainActivity.kt and update 'package' declaration while keeping existing user code.

_For issue 2:_
Could you add an option like '**--delete existing**' to delete the old files after creating the new one.

**Comment by OutdatedGuy** [comment]
> The ideal approach would be to move the existing MainActivity.kt and update 'package' declaration while keeping existing user code.

> Could you add an option like '**--delete existing**' to delete the old files after creating the new one.

Issue with both things is that we don't know the current directory structure where the `MainActivity.kt` is stored.

So I don't know how to locate the `MainActivity.kt` to move or delete it.

**Comment by TrifiAmanallah** [comment]
if no better alternative can be found to auto locate MainActivity.kt ,
we can always ask user to provide a path with a `-- override-existing-activity = my.old.package.MainActivity.kt` for example

**Comment by OutdatedGuy** [comment]
@TrifiAmanallah, new version is up now with this feature
