### ISSUE TITLE
Support config file location param

### ISSUE THREAD

**Issue by milindgoel15** [OutdatedGuy/package_rename#37]
As per docs, the package_rename_config should be kept inside pubspec or at the project's root. Can the command accept a path for the config file? I like keeping all config files in one folder, not the root folder. 

Like `dart run package_rename --config config/package_rename_config.yaml`

**Comment by OutdatedGuy** [comment]
I will provide a feature for that as I get time

**Comment by milindgoel15** [comment]
I will also try it out and create a PR for it.

**Comment by OutdatedGuy** [comment]
@milindgoel15, published in version [1.5.0](https://pub.dev/packages/package_rename/versions/1.5.0)
