### ISSUE TITLE
[windwos] set "CompanyName","OriginalFilename" not work

### ISSUE THREAD

**Issue by xietian0908** [OutdatedGuy/package_rename#40]
package_rename: 1.0.6

![image](https://github.com/OutdatedGuy/package_rename/assets/64937500/ca465ee3-28cc-486d-bdd2-217615bacab5)
"\0" ===> "\\\0" is work

**Comment by OutdatedGuy** [comment]
Hi @xietian0908, I don't understand the problem. Can you elaborate more with sample code and configuration details.

Also try updating the `package_rename` dependency to the latest available.

**Comment by xietian0908** [comment]
I'm sorry, I made a mistake. The version I currently rely on is this one.(package_rename: ^1.5.0)
![image](https://github.com/OutdatedGuy/package_rename/assets/64937500/e059ecda-2279-49d6-a66f-520ee5fcc73b)
As shown in the above diagram, the failure to successfully match the regular expression in the directory under Windows resulted in the unsuccessful replacement of CompanyName, FileDescription, LegalCopyright, and so on.

**Comment by OutdatedGuy** [comment]
@xietian0908, thanks for the report. I tried and can verify it's not working. I'll try to fix it ASAP.

**Comment by OutdatedGuy** [comment]
@xietian0908, new version with the fix published https://pub.dev/packages/package_rename
