### ISSUE TITLE
Avoid PRODUCT_BUNDLE_IDENTIFIER Extension iOS

### ISSUE THREAD

**Issue by chandrabezzo** [OutdatedGuy/package_rename#48]
When we execute command, PRODUCT_BUNDLE_IDENTIFIER from another TARGET like Notification Service or Push Template will be replaced like another bundle identifier. Please avoid to change the suffix of another TARGET. For example if you have com.chandra.app.NotificationService bundle id will be replaced to com.chandra.new. My expectation will changed to com.chandra.new.NotificationService.

**Comment by chandrabezzo** [comment]
After check the code [this line](https://github.com/OutdatedGuy/package_rename/blob/af9511d84a2a58799a9958ce1bb276b83f9f9b11/lib/platforms/ios.dart#L115C59-L115C77) will remove all of PRODUCT_BUNDLE_IDENTIFIER

**Comment by OutdatedGuy** [comment]
Yo @chandrabezzo, I looked into the issue and it's impossible to differentiate between normal target and extension target using regex.

The only hack I found out was that extension targets had their bundle id written in double quotes so I implemented [this](https://github.com/OutdatedGuy/package_rename/blob/af9511d84a2a58799a9958ce1bb276b83f9f9b11/lib/platforms/ios.dart#L133) regex to change them.

Can you wrap the all the bundle id of extension targets in double quotes (`"`) and then try running the package.

**Comment by chandrabezzo** [comment]
I see @OutdatedGuy have you add that approach to readme?

**Comment by OutdatedGuy** [comment]
> I see @OutdatedGuy have you add that approach to readme?

It's supposed to automatically add `"` when creating extension using XCode. IDK why it didn't happened in your case.

But still I'll add a note in readme later.
