### ISSUE TITLE
Web: "name" and "short_name"

### ISSUE THREAD

**Issue by albemala** [OutdatedGuy/package_rename#54]
Hi there, 

first of all, thanks for creating this package! I find it to be super useful.

I'd have a feature request. 

At the moment, for the WEB configuration, we have the `app_name` parameter. 
This parameter changes both `name` and `short_name` in the `manifest.json` file. 
I'd like to request to split the `app_name` parameter into `app_name` and `short_app_name` (or something similar), so that they can be set independently.

Thanks!

**Comment by OutdatedGuy** [comment]
@albemala thanks for mentioning this, I'll implement this once I get some free time.

**Comment by albemala** [comment]
Thank you @OutdatedGuy ! I've opened a PR with these changes, please let me know if you want to change anything in it, happy to do it.
